export enum AuditEventType {
  // Auth
  LOGIN = 'LOGIN',
  MPIN_LOGIN = 'MPIN_LOGIN',
  OTP_VERIFIED = 'OTP_VERIFIED',

  // Broker Session
  BROKER_CONNECTED = 'BROKER_CONNECTED',
  BROKER_DISCONNECTED = 'BROKER_DISCONNECTED',
  BROKER_SESSION_REFRESHED = 'BROKER_SESSION_REFRESHED',
  BROKER_SESSION_FAILED = 'BROKER_SESSION_FAILED',
  BROKER_SESSION_EXPIRED = 'BROKER_SESSION_EXPIRED',

  // Segment
  SEGMENT_ACTIVATED = 'SEGMENT_ACTIVATED',
  SEGMENT_PAUSED = 'SEGMENT_PAUSED',

  // Request logs
  API_REQUEST = 'API_REQUEST',

  // Future-proof
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  CONSENT_GRANTED = 'CONSENT_GRANTED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  ORDER_PLACED = 'ORDER_PLACED',
  TARGET_HIT = 'TARGET_HIT',
  STOPLOSS_HIT = 'STOPLOSS_HIT',

  // Risk Engine Events
  RISK_APPROVED = 'RISK_APPROVED',
  RISK_REJECTED = 'RISK_REJECTED',
  SEGMENT_RISK_LOCKED = 'SEGMENT_RISK_LOCKED',
  SEGMENT_RISK_UNLOCKED = 'SEGMENT_RISK_UNLOCKED',

  // Trading Engine Events
  TRADE_OPENED = 'TRADE_OPENED',
  TRADE_CLOSED = 'TRADE_CLOSED',
  ORDER_FILLED = 'ORDER_FILLED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_REJECTED = 'ORDER_REJECTED',
  SIGNAL_PROCESSED = 'SIGNAL_PROCESSED',
}
