[phases.setup]
nixpkgsArchive = "nixos-unstable"
nixPkgs = ["flutter", "nodejs", "nodePackages.serve"]

[phases.install]
cmds = [
  "flutter config --enable-web",
  "flutter pub get"
]

[phases.build]
cmds = [
  "flutter build web --release --no-tree-shake-icons --no-wasm-dry-run",
  "mkdir -p dist",
  "cp -r build/web/* dist/"
]

[start]
cmd = "serve -s dist -l ${PORT:-80}"