import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:collection/collection.dart';
import 'package:file_picker/file_picker.dart';
import 'package:spresearch_web/services/staff.service.dart';
import 'package:spresearch_web/models/staff.model.dart';
import 'package:spresearch_web/controllers/auth/auth.controller.dart';
import 'package:spresearch_web/services/role_permission.service.dart';
import 'package:spresearch_web/models/role.model.dart';

class StaffController extends GetxController {
  late final StaffService _staffService;
  late final AuthController _authController;
  final _rolePermissionService = Get.put(RolePermissionService());
  var rolesList = <String>[].obs;

  final nameController = TextEditingController();
  final mobileController = TextEditingController();
  final emailController = TextEditingController();
  final mpinController = TextEditingController();
  final departmentController =
      TextEditingController(); // For now using text field, or dropdown if UI requires
  final joiningDateController = TextEditingController();

  final genderController = TextEditingController();
  final dobController = TextEditingController();
  final experienceController = TextEditingController();
  final previousCompanyController = TextEditingController();
  final lastCtcController = TextEditingController();
  final localAddressController = TextEditingController();
  final permanentAddressController = TextEditingController();

  var isLoading = false.obs;
  var staffList = <StaffModel>[].obs;

  var researchersExpanded = true.obs;
  var directorsExpanded = false.obs;
  var managersExpanded = false.obs;
  var researchersPage = 1.obs;
  var directorsPage = 1.obs;
  var managersPage = 1.obs;
  final itemsPerPage = 10;

  var selectedDepartment = ''.obs;

  var isActive = true.obs;
  var autoGeneratedStaffId = ''.obs;

  var isEditing = false.obs;
  var editingStaffId = ''.obs;
  var isViewOnly = false.obs;

  var assignedDirector = Rxn<StaffModel>();

  @override
  void onInit() {
    super.onInit();
    _staffService = Get.find<StaffService>();
    if (Get.isRegistered<AuthController>()) {
      _authController = Get.find<AuthController>();
      if (isDirectorLoggedIn) {
        selectedDepartment.value = 'Manager';
      }
    }
    fetchStaffList();
    fetchRolesList();
  }

  Future<void> fetchRolesList() async {
    try {
      final response = await _rolePermissionService.getRoles();
      if (!response.status.hasError && response.body != null) {
        final list = (response.body['data'] as List? ?? [])
            .map((item) => RoleModel.fromJson(item).name)
            .toList();
        rolesList.assignAll(list);
      }
    } catch (e) {
      debugPrint('Error fetching roles: $e');
    }
  }

  @override
  void onClose() {
    // Dispose all TextEditingControllers to prevent memory leaks
    nameController.dispose();
    mobileController.dispose();
    emailController.dispose();
    mpinController.dispose();
    departmentController.dispose();
    joiningDateController.dispose();

    super.onClose();
  }

  Future<void> fetchStaffList() async {
    isLoading.value = true;
    try {
      final list = await _staffService.getStaffList();

      debugPrint('=== Received ${list.length} staff from backend ===');
      for (var s in list) {
        debugPrint('Staff: ${s.name}, Department: "${s.department}"');
      }

      // If a Director is logged in, filter the list to show themselves, their managers, and all researchers/analysts
      if (isDirectorLoggedIn) {
        final directorId = _authController.user.value?.id;
        staffList.value = list.where((s) {
          final isMe = s.id == directorId;
          final deptLower = s.department.toLowerCase();
          final isMyManager =
              deptLower.contains('manager') &&
              (s.assignedDirector == directorId || s.assignedDirector == null);
          final isResearcherOrAnalyst =
              deptLower.contains('research') || deptLower.contains('analyst');
          return isMe || isMyManager || isResearcherOrAnalyst;
        }).toList();
      } else {
        staffList.value = list;
      }

      if (list.isEmpty) {
        debugPrint('No staff members found');
      } else {
        debugPrint('Loaded ${list.length} staff members');
      }
    } catch (e) {
      debugPrint('Error fetching staff list: $e');

      // Extract user-friendly error message
      final errorMsg = e.toString().replaceAll('Exception: ', '');

      Get.snackbar(
        'Error',
        errorMsg.isEmpty || errorMsg == 'null'
            ? 'Failed to load staff list. Please check your connection and try again.'
            : errorMsg,
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
        duration: const Duration(seconds: 4),
      );
      staffList.value = []; // Ensure list is empty on error
    } finally {
      isLoading.value = false;
    }
  }

  String _normalizeDepartment(String department) {
    // Normalize department to match our standard format
    final normalized = department.toLowerCase().trim();
    if (normalized == 'researcher') return 'Researcher';
    if (normalized == 'director') return 'Director';
    if (normalized == 'manager') return 'Manager';
    if (normalized == 'executive') return 'Executive';
    // Map old 'other staff' / 'other' to 'Manager' for backward compatibility
    if (normalized == 'other staff' || normalized == 'other') {
      return 'Manager';
    }
    // Fallback: default to 'Researcher' to keep the dropdown value valid.
    // Any unknown DB value would otherwise crash the DropdownButton assertion.
    return 'Researcher';
  }

  void populateForEdit(StaffModel staff) {
    isEditing.value = true;
    editingStaffId.value =
        staff.id; // Assuming StaffModel has an 'id' field for the DB ID
    autoGeneratedStaffId.value = staff.staffId;
    nameController.text = staff.name;
    // Remove +91 prefix if present for display in form
    String mobile = staff.mobile;
    if (mobile.startsWith('91')) {
      mobile = mobile.substring(2);
    }
    mobileController.text = mobile;
    emailController.text = staff.email;
    mpinController.text = staff.mpin ?? '';

    // Handle department and role
    // Normalize department to ensure it matches our dropdown values
    selectedDepartment.value = _normalizeDepartment(staff.department);

    if (staff.joiningDate != null) {
      final date = staff.joiningDate!;
      joiningDateController.text =
          "${date.month.toString().padLeft(2, '0')}/${date.day.toString().padLeft(2, '0')}/${date.year}";
    } else {
      joiningDateController.clear();
    }

    isActive.value = staff.status == 'Active';
    isViewOnly.value = staff.isViewOnly;

    genderController.text = staff.gender ?? '';
    dobController.text = staff.dob ?? '';
    experienceController.text = staff.experienceYears?.toString() ?? '';
    previousCompanyController.text = staff.previousCompany ?? '';
    lastCtcController.text = staff.lastCtc ?? '';
    localAddressController.text = staff.localAddress ?? '';
    permanentAddressController.text = staff.permanentAddress ?? '';

    // Handle assigned director for update
    if (staff.assignedDirector != null) {
      // Find staff in list
      final director = staffList.firstWhereOrNull(
        (s) => s.id == staff.assignedDirector,
      );
      if (director != null) {
        assignedDirector.value = director;
      }
    }
  }

  Future<void> saveStaff() async {
    // Validate required fields
    if (nameController.text.trim().isEmpty) {
      Get.snackbar(
        'Validation Error',
        'Please enter full name',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
      return;
    }

    // Validate name length (at least 2 characters, max 100)
    if (nameController.text.trim().length < 2) {
      Get.snackbar(
        'Validation Error',
        'Name must be at least 2 characters long',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
      return;
    }

    if (nameController.text.trim().length > 100) {
      Get.snackbar(
        'Validation Error',
        'Name cannot exceed 100 characters',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
      return;
    }

    if (mobileController.text.trim().isEmpty) {
      Get.snackbar(
        'Validation Error',
        'Please enter mobile number',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
      return;
    }

    // Validate mobile number format
    final mobileStr = mobileController.text.replaceAll(RegExp(r'[^0-9]'), '');

    if (mobileStr.length != 10) {
      Get.snackbar(
        'Validation Error',
        'Please enter a valid 10-digit mobile number',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
      return;
    }

    // Validate mobile number starts with 6-9 (Indian mobile numbers)
    if (!RegExp(r'^[6-9][0-9]{9}$').hasMatch(mobileStr)) {
      Get.snackbar(
        'Validation Error',
        'Mobile number must start with 6, 7, 8, or 9',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
      return;
    }

    final mobileNumber = int.tryParse(mobileStr);

    if (mobileNumber == null) {
      Get.snackbar(
        'Validation Error',
        'Invalid mobile number format',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
      return;
    }

    // Validate email if provided (optional field)
    if (emailController.text.trim().isNotEmpty) {
      final emailRegex = RegExp(
        r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
      );

      if (!emailRegex.hasMatch(emailController.text.trim())) {
        Get.snackbar(
          'Validation Error',
          'Please enter a valid email address',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red[100],
          colorText: Colors.red[900],
        );
        return;
      }
    }

    // Validate MPIN (Only for non-Managers)
    if (selectedDepartment.value.toLowerCase() != 'manager') {
      if (mpinController.text.isNotEmpty) {
        if (mpinController.text.length < 4) {
          Get.snackbar(
            'Validation Error',
            'MPIN must be at least 4 digits',
            snackPosition: SnackPosition.BOTTOM,
            backgroundColor: Colors.red[100],
            colorText: Colors.red[900],
          );
          return;
        }
      } else if (!isEditing.value) {
        Get.snackbar(
          'Validation Error',
          'Please set an MPIN for the new staff member',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red[100],
          colorText: Colors.red[900],
        );
        return;
      }
    }

    // Validate Assigned Director if Manager
    if (selectedDepartment.value.toLowerCase() == 'manager') {
      if (isDirectorLoggedIn) {
        // Auto-assign current director
        // No validation needed here as we handle it in data preparation
      } else {
        // For Admin, ensure a director is selected
        if (assignedDirector.value == null) {
          Get.snackbar(
            'Validation Error',
            'Please assign a director to the manager',
            snackPosition: SnackPosition.BOTTOM,
            backgroundColor: Colors.red[100],
            colorText: Colors.red[900],
          );
          return;
        }
      }
    }

    // Validate joining date if provided
    if (joiningDateController.text.trim().isNotEmpty) {
      final parsedDate = _validateJoiningDate(joiningDateController.text);
      if (parsedDate == null) {
        Get.snackbar(
          'Validation Error',
          'Invalid date format. Please use MM/DD/YYYY format.',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red[100],
          colorText: Colors.red[900],
        );
        return;
      }

      // Check if date is in the future
      if (parsedDate.isAfter(DateTime.now())) {
        Get.snackbar(
          'Validation Error',
          'Joining date cannot be in the future',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red[100],
          colorText: Colors.red[900],
        );
        return;
      }

      // Check if date is too far in the past (e.g., before 1950)
      if (parsedDate.year < 1950) {
        Get.snackbar(
          'Validation Error',
          'Please enter a valid joining date',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red[100],
          colorText: Colors.red[900],
        );
        return;
      }
    }

    if (selectedDepartment.value.isEmpty || selectedDepartment.value == 'Select Department') {
      Get.snackbar(
        'Validation Error',
        'Please select a role',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
      return;
    }

    Map<String, String>? permanentAddressObj;
    if (permanentAddressController.text.trim().isNotEmpty) {
      final text = permanentAddressController.text.trim();
      if (text.startsWith('{') && text.endsWith('}')) {
        final map = <String, String>{};
        final content = text.substring(1, text.length - 1);
        final parts = content.split(',');
        for (final part in parts) {
          final kv = part.split(':');
          if (kv.length >= 2) {
            final key = kv[0].trim();
            final val = kv.sublist(1).join(':').trim();
            map[key] = val;
          }
        }
        permanentAddressObj = {
          "street": map["street"] ?? "",
          "city": map["city"] ?? "",
          "state": map["state"] ?? "",
          "zip": map["zip"] ?? "",
        };
      } else {
        final parts = text.split(',');
        final street = parts.isNotEmpty ? parts[0].trim() : "";
        final city = parts.length > 1 ? parts[1].trim() : "";
        final state = parts.length > 2 ? parts[2].trim() : "";
        permanentAddressObj = {
          "street": street,
          "city": city,
          "state": state,
          "zip": "",
        };
      }
    }

    isLoading.value = true;
    try {
      // Backend expects exact field names including typo "deparment"
      final data = {
        "fullName": nameController.text.trim(),
        "mobileNumber": "+91$mobileStr",
        "emailAddress": emailController.text.trim(),
        "deparment": selectedDepartment.value, // Backend has typo
        "joiningDate": joiningDateController.text.isEmpty
            ? DateTime.now().toIso8601String()
            : _parseJoiningDate(joiningDateController.text),
        "status": isActive.value ? 'Active' : 'Inactive',
        "isViewOnly": isViewOnly.value,
        if (genderController.text.trim().isNotEmpty) "gender": genderController.text.trim(),
        if (dobController.text.trim().isNotEmpty) "dob": dobController.text.trim(),
        if (experienceController.text.trim().isNotEmpty) "experienceYears": int.tryParse(experienceController.text.trim()) ?? 0,
        if (previousCompanyController.text.trim().isNotEmpty) "previousCompany": previousCompanyController.text.trim(),
        if (lastCtcController.text.trim().isNotEmpty) "lastCtc": lastCtcController.text.trim(),
        if (localAddressController.text.trim().isNotEmpty) "localAddress": localAddressController.text.trim(),
        if (permanentAddressObj != null) "permanentAddress": permanentAddressObj,
      };

      if (selectedDepartment.value.toLowerCase() != 'manager' &&
          mpinController.text.isNotEmpty) {
        data["mpin"] = mpinController.text.trim();
      }

      // Handle assigned director
      if (selectedDepartment.value.toLowerCase() == 'manager') {
        if (isDirectorLoggedIn) {
          data["assignedDirector"] = _authController.user.value!.id;
          data["assignedDirectorName"] = _authController.user.value!.fullName;
        } else if (assignedDirector.value != null) {
          data["assignedDirector"] = assignedDirector.value!.id;
          data["assignedDirectorName"] = assignedDirector.value!.name;
        }
      }

      // Only include staffId for update operations
      if (isEditing.value) {
        data["staffId"] = autoGeneratedStaffId.value;
      }

      debugPrint('Submitting staff data: $data');
      print('DEBUG: isViewOnly value being sent: ${data["isViewOnly"]}');

      bool success = false;
      String? errorMessage;

      try {
        if (isEditing.value) {
          success = await _staffService.updateStaff(editingStaffId.value, data);
        } else {
          success = await _staffService.createStaff(data);
        }
      } catch (serviceError) {
        errorMessage = serviceError.toString().replaceAll('Exception: ', '');
        debugPrint('Service error: $errorMessage');
      }

      if (success) {
        Get.back();
        Get.snackbar(
          'Success',
          isEditing.value
              ? 'Staff member updated successfully'
              : 'Staff member added successfully',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.green[100],
          colorText: Colors.green[900],
          duration: const Duration(seconds: 3),
        );
        resetForm();
        await fetchStaffList(); // Refresh list
      } else {
        Get.snackbar(
          'Error',
          errorMessage ??
              (isEditing.value
                  ? 'Failed to update staff member. Please try again.'
                  : 'Failed to add staff member. Please try again.'),
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red[100],
          colorText: Colors.red[900],
          duration: const Duration(seconds: 4),
        );
      }
    } catch (e) {
      debugPrint('Exception in saveStaff: $e');
      Get.snackbar(
        'Error',
        'An unexpected error occurred. Please try again.',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
    } finally {
      isLoading.value = false;
    }
  }

  String _parseJoiningDate(String dateStr) {
    try {
      // Input format: mm/dd/yyyy
      final parts = dateStr.split('/');
      if (parts.length == 3) {
        final month = int.parse(parts[0]);
        final day = int.parse(parts[1]);
        final year = int.parse(parts[2]);

        // Validate month and day ranges
        if (month < 1 || month > 12 || day < 1 || day > 31) {
          throw FormatException('Invalid date values');
        }

        final date = DateTime(year, month, day);
        return date.toIso8601String();
      }
    } catch (e) {
      debugPrint('Error parsing date: $e');
    }
    return DateTime.now().toIso8601String();
  }

  DateTime? _validateJoiningDate(String dateStr) {
    try {
      final parts = dateStr.split('/');
      if (parts.length != 3) return null;

      final month = int.tryParse(parts[0]);
      final day = int.tryParse(parts[1]);
      final year = int.tryParse(parts[2]);

      if (month == null || day == null || year == null) return null;

      // Validate ranges
      if (month < 1 || month > 12 || day < 1 || day > 31) return null;
      if (year < 1900 || year > 2100) return null;

      return DateTime(year, month, day);
    } catch (e) {
      return null;
    }
  }

  void resetForm() {
    isEditing.value = false;
    editingStaffId.value = '';
    autoGeneratedStaffId.value = '';
    nameController.clear();
    mobileController.clear();
    emailController.clear();
    mpinController.clear();
    departmentController.clear();
    joiningDateController.clear();
    genderController.clear();
    dobController.clear();
    experienceController.clear();
    previousCompanyController.clear();
    lastCtcController.clear();
    localAddressController.clear();
    permanentAddressController.clear();

    selectedDepartment.value = isDirectorLoggedIn ? 'Manager' : '';

    isActive.value = true;
    isViewOnly.value = false;
    assignedDirector.value = null;
  }

  bool get isDirectorLoggedIn {
    if (!Get.isRegistered<AuthController>()) return false;
    return _authController.user.value?.isDirector == true;
  }

  bool get isAdminLoggedIn {
    if (!Get.isRegistered<AuthController>()) return false;
    return _authController.user.value?.isAdmin == true;
  }

  String get currentDirectorName {
    if (!Get.isRegistered<AuthController>()) return '';
    return _authController.user.value?.fullName ?? '';
  }

  List<StaffModel> get availableDirectors {
    final directors = staffList
        .where((s) => s.department.toLowerCase().trim().contains('director'))
        .toList();
    return directors;
  }

  List<StaffModel> get allResearchers {
    final list = staffList
        .where((s) {
          final dept = s.department.toLowerCase().trim();
          return dept.contains('research') || dept.contains('analyst');
        })
        .toList();
    return list;
  }

  List<StaffModel> get allManagers {
    final list = staffList.where((s) {
      final dept = s.department.toLowerCase().trim();
      return dept.contains('manager');
    }).toList();
    return list;
  }

  List<StaffModel> get otherStaff {
    final list = staffList.where((s) {
      final dept = s.department.toLowerCase().trim();
      final isDirector = dept.contains('director');
      final isResearcher = dept.contains('research') || dept.contains('analyst');
      final isManager = dept.contains('manager');
      return !isDirector && !isResearcher && !isManager;
    }).toList();
    return list;
  }

  List<StaffModel> get paginatedDirectors {
    if (availableDirectors.isEmpty) return [];

    // Ensure page is within valid bounds
    if (directorsPage.value < 1) {
      directorsPage.value = 1;
    }

    final start = (directorsPage.value - 1) * itemsPerPage;
    if (start >= availableDirectors.length && availableDirectors.isNotEmpty) {
      // Reset to last valid page
      directorsPage.value = directorsTotalPages;
      final newStart = (directorsPage.value - 1) * itemsPerPage;
      final newEnd = newStart + itemsPerPage;
      return availableDirectors.sublist(
        newStart,
        newEnd > availableDirectors.length ? availableDirectors.length : newEnd,
      );
    }

    final end = start + itemsPerPage;
    return availableDirectors.sublist(
      start,
      end > availableDirectors.length ? availableDirectors.length : end,
    );
  }

  List<StaffModel> get paginatedResearchers {
    if (allResearchers.isEmpty) return [];

    // Ensure page is within valid bounds
    if (researchersPage.value < 1) {
      researchersPage.value = 1;
    }

    final start = (researchersPage.value - 1) * itemsPerPage;
    if (start >= allResearchers.length && allResearchers.isNotEmpty) {
      // Reset to last valid page
      researchersPage.value = researchersTotalPages;
      final newStart = (researchersPage.value - 1) * itemsPerPage;
      final newEnd = newStart + itemsPerPage;
      return allResearchers.sublist(
        newStart,
        newEnd > allResearchers.length ? allResearchers.length : newEnd,
      );
    }

    final end = start + itemsPerPage;
    return allResearchers.sublist(
      start,
      end > allResearchers.length ? allResearchers.length : end,
    );
  }

  List<StaffModel> get paginatedManagers {
    if (allManagers.isEmpty) return [];

    // Ensure page is within valid bounds
    if (managersPage.value < 1) {
      managersPage.value = 1;
    }

    final start = (managersPage.value - 1) * itemsPerPage;
    if (start >= allManagers.length && allManagers.isNotEmpty) {
      // Reset to last valid page
      managersPage.value = managersTotalPages;
      final newStart = (managersPage.value - 1) * itemsPerPage;
      final newEnd = newStart + itemsPerPage;
      return allManagers.sublist(
        newStart,
        newEnd > allManagers.length ? allManagers.length : newEnd,
      );
    }

    final end = start + itemsPerPage;
    return allManagers.sublist(
      start,
      end > allManagers.length ? allManagers.length : end,
    );
  }

  var otherStaffPage = 1.obs;
  var otherStaffExpanded = false.obs;

  List<StaffModel> get paginatedOtherStaff {
    if (otherStaff.isEmpty) return [];

    if (otherStaffPage.value < 1) {
      otherStaffPage.value = 1;
    }

    final start = (otherStaffPage.value - 1) * itemsPerPage;
    if (start >= otherStaff.length && otherStaff.isNotEmpty) {
      otherStaffPage.value = otherStaffTotalPages;
      final newStart = (otherStaffPage.value - 1) * itemsPerPage;
      final newEnd = newStart + itemsPerPage;
      return otherStaff.sublist(
        newStart,
        newEnd > otherStaff.length ? otherStaff.length : newEnd,
      );
    }

    final end = start + itemsPerPage;
    return otherStaff.sublist(
      start,
      end > otherStaff.length ? otherStaff.length : end,
    );
  }

  int get directorsTotalPages => availableDirectors.isEmpty
      ? 1
      : (availableDirectors.length / itemsPerPage).ceil();

  int get researchersTotalPages => allResearchers.isEmpty
      ? 1
      : (allResearchers.length / itemsPerPage).ceil();
  int get managersTotalPages =>
      allManagers.isEmpty ? 1 : (allManagers.length / itemsPerPage).ceil();
  int get otherStaffTotalPages =>
      otherStaff.isEmpty ? 1 : (otherStaff.length / itemsPerPage).ceil();

  // Department dropdown options for staff creation
  List<String> get availableDepartments {
    if (isDirectorLoggedIn) {
      return ['Manager'];
    }
    if (rolesList.isNotEmpty) {
      return rolesList;
    }
    return ['Researcher', 'Director', 'Manager', 'Executive'];
  }

  void updateDepartment(String dept) {
    selectedDepartment.value = dept;
  }

  Future<void> deleteStaff(String staffId, String staffName) async {
    // Show confirmation dialog
    final confirmed = await Get.dialog<bool>(
      Dialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        child: Container(
          width: 400,
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(
                    Icons.warning_amber_rounded,
                    color: Colors.orange[700],
                    size: 28,
                  ),
                  const SizedBox(width: 12),
                  Text(
                    'Confirm Deletion',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.w600,
                      color: Colors.grey[800],
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              Text(
                'Are you sure you want to delete $staffName?',
                style: TextStyle(
                  fontSize: 14,
                  color: Colors.grey[700],
                  height: 1.5,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'This action cannot be undone. All data associated with this staff member will be permanently removed.',
                style: TextStyle(
                  fontSize: 13,
                  color: Colors.grey[600],
                  height: 1.5,
                ),
              ),
              const SizedBox(height: 24),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: () => Get.back(result: false),
                    style: TextButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 10,
                      ),
                    ),
                    child: Text(
                      'Cancel',
                      style: TextStyle(
                        color: Colors.grey[700],
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  ElevatedButton(
                    onPressed: () => Get.back(result: true),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.red[600],
                      padding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 10,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(6),
                      ),
                    ),
                    child: const Text(
                      'Delete',
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );

    if (confirmed == true) {
      isLoading.value = true;
      try {
        final success = await _staffService.deleteStaff(staffId);
        if (success) {
          Get.snackbar(
            'Success',
            'Staff member deleted successfully',
            snackPosition: SnackPosition.BOTTOM,
            backgroundColor: Colors.green[100],
            colorText: Colors.green[900],
          );
          await fetchStaffList();
        } else {
          Get.snackbar(
            'Error',
            'Failed to delete staff member',
            snackPosition: SnackPosition.BOTTOM,
            backgroundColor: Colors.red[100],
            colorText: Colors.red[900],
          );
        }
      } catch (e) {
        Get.snackbar(
          'Error',
          'An error occurred while deleting staff member',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red[100],
          colorText: Colors.red[900],
        );
      } finally {
        isLoading.value = false;
      }
    }
  }

  Future<void> toggleStaffStatus(String staffId, bool isActive) async {
    final newStatus = isActive ? 'Active' : 'Deactivated';

    // Optimistic update logic could go here

    try {
      // Assuming updateStaff method handles partial updates
      // If not, we need to pass strict structure or fetch-modify-save
      // Since `staffReset` in backend seems to update fields, checking if it handles partial
      // Backend `staffReset` updates: fullName, mobileNumber, emailAddress, deparment, etc.
      // It DOES expect these fields.
      // If I send ONLY status, other fields might be overwritten with undefined if not handled carefully in backend.
      // Let's check backend `staffReset`...
      // Backend: `let { fullName, ... } = body`.
      // `staff.fullName = fullName`. If fullName is undefined, it sets undefined?
      // Mongoose might ignore undefined for updates if not explicitly set to null, but let's be safe.

      // Wait, `staffReset` implementation:
      // staff.fullName = fullName
      // It assigns directly. So if I send minimal body, it might break data.

      // BUT, I can find the staff model in `staffList` and send all data + new status.

      final staff = staffList.firstWhereOrNull((s) => s.id == staffId);
      if (staff == null) {
        Get.snackbar('Error', 'Staff not found locally');
        return;
      }

      final data = {
        "fullName": staff.name,
        "mobileNumber": staff.mobile, // Ensure format is correct
        "emailAddress": staff.email,
        "deparment": staff.department,
        "joiningDate": staff.joiningDate?.toIso8601String(),
        "status": newStatus,
        "staffId": staff.staffId,
        // Include MPIN only if it's not null/empty?
        "mpin": staff.mpin,
        // Assigned Director
        "assignedDirector": staff.assignedDirector,
        "assignedDirectorName": staff.assignedDirectorName,
      };

      // Fix mobile number if it has +91 or not
      // Backend expects usually numbers, stored as Number or String?
      // Model says Number.
      // `staffReset` takes body.mobileNumber.

      final success = await _staffService.updateStaff(staffId, data);

      if (success) {
        Get.snackbar(
          'Success',
          'Staff status updated to $newStatus',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.green[100],
          colorText: Colors.green[900],
          duration: const Duration(seconds: 2),
        );
        await fetchStaffList(); // Refresh to ensure sync
      } else {
        Get.snackbar(
          'Error',
          'Failed to assign status',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red[100],
          colorText: Colors.red[900],
        );
      }
    } catch (e) {
      debugPrint('Error toggling status: $e');
      Get.snackbar(
        'Error',
        'An error occurred: $e',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red[100],
        colorText: Colors.red[900],
      );
    }
  }

  Future<void> pickAndUploadDoc(String id, String type) async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: type == 'video' ? ['mp4', 'mov', 'avi'] : ['jpg', 'jpeg', 'png', 'pdf'],
      );

      if (result != null && result.files.single.bytes != null) {
        isLoading.value = true;
        final res = type == 'video'
            ? await _staffService.uploadStaffVideo(id, result.files.single.bytes!, result.files.single.name)
            : await _staffService.uploadStaffDocument(id, type, result.files.single.bytes!, result.files.single.name);

        isLoading.value = false;
        if (res.success) {
          await fetchStaffList(); // reload staff list to update file URLs
          Get.snackbar('Upload Complete', '${type.toUpperCase()} uploaded successfully', backgroundColor: Colors.green.withOpacity(0.1));
        } else {
          Get.snackbar('Upload Failed', res.message ?? 'An error occurred', backgroundColor: Colors.red.withOpacity(0.1));
        }
      }
    } catch (e) {
      isLoading.value = false;
      Get.snackbar('Error', 'Failed to upload: $e', backgroundColor: Colors.red.withOpacity(0.1));
    }
  }
}
