import { Module, Global } from '@nestjs/common';
import { BullModule } from '@nestjs/bullmq';
import { Queues } from './queue.constants';
import { QueueService } from './queues.service';
import {
  SignalQueueEventsListener,
  OrderPlacementQueueEventsListener,
  NotificationQueueEventsListener,
  OrderMonitoringQueueEventsListener,
  OutboxQueueEventsListener,
  WebsocketQueueEventsListener,
  ReportGenerationQueueEventsListener,
  ReportExportQueueEventsListener,
  AnalyticsSnapshotQueueEventsListener,
  PositionRebuildQueueEventsListener,
  ReconciliationQueueEventsListener,
  RiskRecalculateQueueEventsListener,
  AnalyticsRecalculateQueueEventsListener,
  EmailQueueEventsListener,
  SmsQueueEventsListener,
  WhatsAppQueueEventsListener,
  PushQueueEventsListener,
} from './dlq.handler';

@Global()
@Module({
  imports: [
    BullModule.registerQueue({ name: Queues.SIGNAL_PROCESSING }),
    BullModule.registerQueue({ name: Queues.ORDER_PLACEMENT }),
    BullModule.registerQueue({ name: Queues.ORDER_MONITORING }),
    BullModule.registerQueue({ name: Queues.NOTIFICATION }),
    BullModule.registerQueue({ name: Queues.SIGNAL_DLQ }),
    BullModule.registerQueue({ name: Queues.ORDER_DLQ }),
    BullModule.registerQueue({ name: Queues.ORDER_MONITORING_DLQ }),
    BullModule.registerQueue({ name: Queues.NOTIFICATION_DLQ }),
    BullModule.registerQueue({ name: Queues.OUTBOX_DISPATCHER }),
    BullModule.registerQueue({ name: Queues.OUTBOX_DISPATCHER_DLQ }),
    BullModule.registerQueue({ name: Queues.WEBSOCKET }),
    BullModule.registerQueue({ name: Queues.WEBSOCKET_DLQ }),
    BullModule.registerQueue({ name: Queues.REPORT_GENERATION }),
    BullModule.registerQueue({ name: Queues.REPORT_GENERATION_DLQ }),
    BullModule.registerQueue({ name: Queues.REPORT_EXPORT }),
    BullModule.registerQueue({ name: Queues.REPORT_EXPORT_DLQ }),
    BullModule.registerQueue({ name: Queues.ANALYTICS_SNAPSHOT }),
    BullModule.registerQueue({ name: Queues.ANALYTICS_SNAPSHOT_DLQ }),
    BullModule.registerQueue({ name: Queues.POSITION_REBUILD }),
    BullModule.registerQueue({ name: Queues.POSITION_REBUILD_DLQ }),
    BullModule.registerQueue({ name: Queues.RECONCILIATION }),
    BullModule.registerQueue({ name: Queues.RECONCILIATION_DLQ }),
    BullModule.registerQueue({ name: Queues.RISK_RECALCULATE }),
    BullModule.registerQueue({ name: Queues.RISK_RECALCULATE_DLQ }),
    BullModule.registerQueue({ name: Queues.ANALYTICS_RECALCULATE }),
    BullModule.registerQueue({ name: Queues.ANALYTICS_RECALCULATE_DLQ }),
    BullModule.registerQueue({ name: Queues.EMAIL }),
    BullModule.registerQueue({ name: Queues.EMAIL_DLQ }),
    BullModule.registerQueue({ name: Queues.SMS }),
    BullModule.registerQueue({ name: Queues.SMS_DLQ }),
    BullModule.registerQueue({ name: Queues.WHATSAPP }),
    BullModule.registerQueue({ name: Queues.WHATSAPP_DLQ }),
    BullModule.registerQueue({ name: Queues.PUSH }),
    BullModule.registerQueue({ name: Queues.PUSH_DLQ }),
    ...Array.from({ length: 10 }, (_, i) => BullModule.registerQueue({ name: `analytics-snapshot-${i}` })),
    ...Array.from({ length: 10 }, (_, i) => BullModule.registerQueue({ name: `analytics-snapshot-dlq-${i}` })),
  ],
  providers: [
    QueueService,
    SignalQueueEventsListener,
    OrderPlacementQueueEventsListener,
    NotificationQueueEventsListener,
    OrderMonitoringQueueEventsListener,
    OutboxQueueEventsListener,
    WebsocketQueueEventsListener,
    ReportGenerationQueueEventsListener,
    ReportExportQueueEventsListener,
    AnalyticsSnapshotQueueEventsListener,
    PositionRebuildQueueEventsListener,
    ReconciliationQueueEventsListener,
    RiskRecalculateQueueEventsListener,
    AnalyticsRecalculateQueueEventsListener,
    EmailQueueEventsListener,
    SmsQueueEventsListener,
    WhatsAppQueueEventsListener,
    PushQueueEventsListener,
  ],
  exports: [QueueService],
})
export class QueuesModule {}
