import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:spresearch_web/config/theme.config.dart';
import 'package:spresearch_web/controllers/dashboard/dashboard.controller.dart';

class SalesMetricsChart extends StatelessWidget {
  const SalesMetricsChart({super.key});

  @override
  Widget build(BuildContext context) {
    final controller = Get.find<DashboardController>();
    final currencyFormatter = NumberFormat.currency(
      locale: 'en_IN',
      symbol: '₹',
      decimalDigits: 0,
    );

    return Obx(() {
      final staffList = controller.staffPerformanceList;
      final deptSales = controller.departmentSales;
      final maxRevenue = staffList.isNotEmpty
          ? staffList
              .map((e) => (e['totalSalesAmount'] ?? 0).toDouble())
              .reduce((a, b) => a > b ? a : b)
          : 1.0;

      final safeMaxRevenue = maxRevenue > 0 ? maxRevenue : 1.0;

      return LayoutBuilder(
        builder: (context, constraints) {
          final isDesktop = constraints.maxWidth > 900;

          return Flex(
            direction: isDesktop ? Axis.horizontal : Axis.vertical,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Staff Revenue Comparison Chart Card
              Expanded(
                flex: isDesktop ? 3 : 0,
                child: Container(
                  padding: const EdgeInsets.all(24),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: AppTheme.gray200),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.02),
                        blurRadius: 10,
                        offset: const Offset(0, 4),
                      ),
                    ],
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Row(
                            children: [
                              Icon(
                                Icons.bar_chart_rounded,
                                color: AppTheme.primaryBlue,
                                size: 22,
                              ),
                              SizedBox(width: 10),
                              Text(
                                'Staff Sales Revenue Chart',
                                style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w700,
                                  color: AppTheme.gray900,
                                ),
                              ),
                            ],
                          ),
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 10,
                              vertical: 4,
                            ),
                            decoration: BoxDecoration(
                              color: AppTheme.primaryBlue.withOpacity(0.08),
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: const Text(
                              'Ranked by Sales',
                              style: TextStyle(
                                fontSize: 11,
                                fontWeight: FontWeight.w600,
                                color: AppTheme.primaryBlue,
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      const Text(
                        'Comparative revenue generated by individual sales representatives',
                        style: TextStyle(
                          fontSize: 12,
                          color: AppTheme.gray600,
                        ),
                      ),
                      const SizedBox(height: 24),
                      if (staffList.isEmpty)
                        const Padding(
                          padding: EdgeInsets.all(32.0),
                          child: Center(
                            child: Text(
                              'No staff sales metrics available yet.',
                              style: TextStyle(color: AppTheme.gray600),
                            ),
                          ),
                        )
                      else
                        ListView.separated(
                          shrinkWrap: true,
                          physics: const NeverScrollableScrollPhysics(),
                          itemCount: staffList.length.clamp(0, 6),
                          separatorBuilder: (context, index) =>
                              const SizedBox(height: 16),
                          itemBuilder: (context, index) {
                            final item = staffList[index];
                            final revenue =
                                (item['totalSalesAmount'] ?? 0).toDouble();
                            final percentage =
                                (revenue / safeMaxRevenue).clamp(0.05, 1.0);
                            final name = item['name'] ?? 'Staff Member';
                            final orders = item['ordersCount'] ?? 0;

                            return Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Row(
                                  mainAxisAlignment:
                                      MainAxisAlignment.spaceBetween,
                                  children: [
                                    Row(
                                      children: [
                                        Text(
                                          '#${index + 1}',
                                          style: const TextStyle(
                                            fontSize: 12,
                                            fontWeight: FontWeight.w700,
                                            color: AppTheme.primaryBlue,
                                          ),
                                        ),
                                        const SizedBox(width: 8),
                                        Text(
                                          name,
                                          style: const TextStyle(
                                            fontSize: 13,
                                            fontWeight: FontWeight.w600,
                                            color: AppTheme.gray900,
                                          ),
                                        ),
                                        const SizedBox(width: 8),
                                        Text(
                                          '($orders orders)',
                                          style: const TextStyle(
                                            fontSize: 11,
                                            color: AppTheme.gray600,
                                          ),
                                        ),
                                      ],
                                    ),
                                    Text(
                                      currencyFormatter.format(revenue),
                                      style: const TextStyle(
                                        fontSize: 13,
                                        fontWeight: FontWeight.w700,
                                        color: AppTheme.gray900,
                                      ),
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 8),
                                Stack(
                                  children: [
                                    Container(
                                      height: 10,
                                      width: double.infinity,
                                      decoration: BoxDecoration(
                                        color: AppTheme.gray100,
                                        borderRadius:
                                            BorderRadius.circular(5),
                                      ),
                                    ),
                                    FractionallySizedBox(
                                      widthFactor: percentage,
                                      child: Container(
                                        height: 10,
                                        decoration: BoxDecoration(
                                          gradient: LinearGradient(
                                            colors: [
                                              AppTheme.primaryBlue,
                                              AppTheme.primaryBlue
                                                  .withOpacity(0.7),
                                            ],
                                          ),
                                          borderRadius:
                                              BorderRadius.circular(5),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            );
                          },
                        ),
                    ],
                  ),
                ),
              ),

              if (isDesktop) const SizedBox(width: 24) else const SizedBox(height: 24),

              // Department Breakdown Chart Card
              Expanded(
                flex: isDesktop ? 2 : 0,
                child: Container(
                  padding: const EdgeInsets.all(24),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: AppTheme.gray200),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.02),
                        blurRadius: 10,
                        offset: const Offset(0, 4),
                      ),
                    ],
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Row(
                        children: [
                          Icon(
                            Icons.donut_large_rounded,
                            color: Colors.purple,
                            size: 22,
                          ),
                          SizedBox(width: 10),
                          Text(
                            'Department Distribution',
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.w700,
                              color: AppTheme.gray900,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      const Text(
                        'Sales revenue distribution across organization departments',
                        style: TextStyle(
                          fontSize: 12,
                          color: AppTheme.gray600,
                        ),
                      ),
                      const SizedBox(height: 24),
                      if (deptSales.isEmpty)
                        const Padding(
                          padding: EdgeInsets.all(32.0),
                          child: Center(
                            child: Text(
                              'No department sales distribution data.',
                              style: TextStyle(color: AppTheme.gray600),
                            ),
                          ),
                        )
                      else
                        ListView.separated(
                          shrinkWrap: true,
                          physics: const NeverScrollableScrollPhysics(),
                          itemCount: deptSales.length,
                          separatorBuilder: (context, index) =>
                              const SizedBox(height: 16),
                          itemBuilder: (context, index) {
                            final item = deptSales[index];
                            final dept = item['department'] ?? 'Sales';
                            final revenue =
                                (item['totalSalesAmount'] ?? 0).toDouble();

                            final totalDeptRevenue = deptSales.fold<double>(
                              0.0,
                              (acc, elem) =>
                                  acc +
                                  (elem['totalSalesAmount'] ?? 0).toDouble(),
                            );
                            final share = totalDeptRevenue > 0
                                ? (revenue / totalDeptRevenue * 100)
                                    .round()
                                : 0;

                            final color = Colors.primaries[
                                index % Colors.primaries.length];

                            return Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Row(
                                  mainAxisAlignment:
                                      MainAxisAlignment.spaceBetween,
                                  children: [
                                    Row(
                                      children: [
                                        Container(
                                          width: 10,
                                          height: 10,
                                          decoration: BoxDecoration(
                                            color: color,
                                            shape: BoxShape.circle,
                                          ),
                                        ),
                                        const SizedBox(width: 8),
                                        Text(
                                          dept,
                                          style: const TextStyle(
                                            fontSize: 13,
                                            fontWeight: FontWeight.w600,
                                            color: AppTheme.gray900,
                                          ),
                                        ),
                                      ],
                                    ),
                                    Text(
                                      '${currencyFormatter.format(revenue)} ($share%)',
                                      style: const TextStyle(
                                        fontSize: 13,
                                        fontWeight: FontWeight.w700,
                                        color: AppTheme.gray900,
                                      ),
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 8),
                                ClipRRect(
                                  borderRadius: BorderRadius.circular(4),
                                  child: LinearProgressIndicator(
                                    value: totalDeptRevenue > 0
                                        ? revenue / totalDeptRevenue
                                        : 0,
                                    backgroundColor: AppTheme.gray100,
                                    color: color,
                                    minHeight: 8,
                                  ),
                                ),
                              ],
                            );
                          },
                        ),
                    ],
                  ),
                ),
              ),
            ],
          );
        },
      );
    });
  }
}
